### ISSUE TITLE
Different opacity values of logo and top bar

### ISSUE THREAD

**Issue by GoranStoyanov** [dev-labs-bg/devlabs-website#23]
<img width="125" alt="screen shot 2017-07-06 at 7 54 15 pm" src="https://user-images.githubusercontent.com/1016174/27922931-4fa0bb92-6285-11e7-8539-fd141a5ab339.png">

**Comment by superKalo** [comment]
Here's a fixed resource file: [devlabs_logo2](https://user-images.githubusercontent.com/2548061/28165233-a415bef6-67db-11e7-8771-444766eaa2ae.png)
